<a href="https://colab.research.google.com/github/Evgenius87/Data_Science_hw/blob/main/Hw1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1 Створіть одновимірний масив (вектор) з першими 10-ма натуральними числами та виведіть його значення.

In [2]:
import numpy as np
vector = np.arange(1,11)
print(vector)

[ 1  2  3  4  5  6  7  8  9 10]


#2 Створіть двовимірний масив (матрицю) розміром 3x3, заповніть його нулями та виведіть його значення.

In [ ]:
matrix = np.zeros((3, 3), dtype="u4")
print(matrix)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


#3 Створіть масив розміром 5x5, заповніть його випадковими цілими числами в діапазоні від 1 до 10 та виведіть його значення.

In [ ]:
matrix = np.random.randint(1, 11, size=(5,5), dtype=int)
print(matrix)

[[10  8  8  8  8]
 [ 1  3  1  3  1]
 [ 8  9  5  3  1]
 [ 4  7  9  7  3]
 [ 4  5  6  5  8]]


#4 Створіть масив розміром 4x4, заповніть його випадковими дійсними числами в діапазоні від 0 до 1 та виведіть його значення.

In [ ]:
matrix = np.random.randint(0, 2, size=(4,4), dtype=int)
print(matrix)

[[0 0 0 1]
 [0 0 0 0]
 [0 1 0 1]
 [1 1 0 0]]


#5 Створіть два одновимірних масиви розміром 5, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте на них поелементні операції додавання, віднімання та множення.

In [ ]:
vector_1 = np.random.randint(1, 11, size=5, dtype=int)
vector_2 = np.random.randint(1, 11, size=5, dtype=int)
print(f"vector_1: {vector_1}")
print(f"vector_2: {vector_2}")
print(f"addition: \n{vector_1 + vector_2}")
print(f"subtraction: \n{vector_1 - vector_2}")
print(f"multiplication: \n{vector_1 * vector_2}")

vector_1: [3 7 3 5 9]
vector_2: [8 7 7 2 5]
addition: 
[11 14 10  7 14]
subtraction: 
[-5  0 -4  3  4]
multiplication: 
[24 49 21 10 45]


#6 Створіть два вектори розміром 7, заповніть довільними числами та знайдіть їх скалярний добуток.

In [ ]:
vector_1 = np.random.randint(1, 11, size=7, dtype=int)
vector_2 = np.random.randint(1, 11, size=7, dtype=int)
print(f"vector_1: {vector_1}")
print(f"vector_2: {vector_2}")
print(f"scalar product: {np.dot(vector_1, vector_2)}")

vector_1: [6 7 7 2 6 7 8]
vector_2: [5 2 8 7 4 7 9]
scalar product: 259


#7 Створіть дві матриці розміром 2x2 та 2x3, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте їх між собою.

In [ ]:
matrix_1 = np.random.randint(1, 11, size=(2, 2), dtype=int)
matrix_2 = np.random.randint(1, 11, size=(2, 3), dtype=int)
mult_mtrx = np.dot(matrix_1, matrix_2)
print(f"matrix_1:\n{matrix_1}")
print(f"matrix_2:\n{matrix_2}")
print(f"multiplied  matrix:\n{mult_mtrx}")

matrix_1:
[[8 4]
 [9 1]]
matrix_2:
[[8 8 1]
 [7 2 3]]
multiplied  matrix:
[[92 72 20]
 [79 74 12]]


#8 Створіть матрицю розміром 3x3, заповніть її випадковими цілими числами в діапазоні від 1 до 10 та знайдіть її обернену матрицю.

In [ ]:
matrix = np.random.randint(1, 11, size=(3, 3), dtype=int)
matrix_inv = np.linalg.inv(matrix)
print(f"origin matrix:\n{matrix}")
print(f"reversed matrix:\n{matrix_inv}")

origin matrix:
[[ 6  9  1]
 [ 4  5  2]
 [10  4 10]]
reversed matrix:
[[ 1.10526316 -2.26315789  0.34210526]
 [-0.52631579  1.31578947 -0.21052632]
 [-0.89473684  1.73684211 -0.15789474]]


#9 Створіть матрицю розміром 4x4, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та транспонуйте її.

In [ ]:
matrix = np.random.randint(0, 2, size=(4, 4), dtype=int)
trans_matrix = matrix.T
print(f"origin matrix:\n{matrix}")
print(f"transposed matrix:\n{trans_matrix}")

origin matrix:
[[1 0 1 0]
 [0 1 0 0]
 [1 0 1 0]
 [1 0 1 1]]
transposed matrix:
[[1 0 1 1]
 [0 1 0 0]
 [1 0 1 1]
 [0 0 0 1]]


#10 Створіть матрицю розміром 3x4 та вектор розміром 4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та перемножте матрицю на вектор.

In [4]:
matrix = np.random.randint(1, 11, size=(3, 4), dtype=int)
vector = np.random.randint(1, 11, size=4, dtype=int)
matrix_x_vector = np.dot(matrix, vector)
print(f"matrix:\n{matrix}")
print(f"vector: {vector}")
print(f"matrix_x_vector:\n{matrix_x_vector}")

matrix:
[[4 1 3 1]
 [2 3 4 5]
 [1 6 6 2]]
vector: [1 7 5 1]
matrix_x_vector:
[27 48 75]


#11 Створіть матрицю розміром 2x3 та вектор розміром 3, заповніть їх випадковими дійсними числами в діапазоні від 0 до 1 та перемножте матрицю на вектор.

In [5]:
matrix = np.random.randint(0, 2, size=(2, 3), dtype=int)
vector = np.random.randint(0, 2, size=3, dtype=int)
matrix_x_vector = np.dot(matrix, vector)
print(f"matrix:\n{matrix}")
print(f"vector: {vector}")
print(f"matrix_x_vector:\n{matrix_x_vector}")

matrix:
[[0 0 0]
 [0 1 1]]
vector: [1 0 1]
matrix_x_vector:
[0 1]


#12 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та виконайте їхнє поелементне множення.

In [9]:
matrix_1 = np.random.randint(1, 11, size=(2, 2), dtype=int)
matrix_2 = np.random.randint(1, 11, size=(2, 2), dtype=int)
mult_mtrx = np.multiply(matrix_1, matrix_2)
print(f"matrix_1:\n{matrix_1}")
print(f"matrix_2:\n{matrix_2}")
print(f"multiplied  matrix:\n{mult_mtrx}")

matrix_1:
[[ 3 10]
 [ 1  6]]
matrix_2:
[[6 9]
 [1 8]]
multiplied  matrix:
[[18 90]
 [ 1 48]]


#13 Створіть дві матриці розміром 2x2, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їх добуток.

In [10]:
matrix_1 = np.random.randint(1, 11, size=(2, 2), dtype=int)
matrix_2 = np.random.randint(1, 11, size=(2, 2), dtype=int)
mult_mtrx = np.dot(matrix_1, matrix_2)
print(f"matrix_1:\n{matrix_1}")
print(f"matrix_2:\n{matrix_2}")
print(f"multiplied  matrix:\n{mult_mtrx}")

matrix_1:
[[3 3]
 [2 7]]
matrix_2:
[[4 5]
 [2 3]]
multiplied  matrix:
[[18 24]
 [22 31]]


#14 Створіть матрицю розміром 5x5, заповніть її випадковими цілими числами в діапазоні від 1 до 100 та знайдіть суму елементів матриці.

In [14]:
matrix = np.random.randint(1, 101, size=(5, 5), dtype=int)
print(f"matrix:\n{matrix}")
print(f"sum of elements = {matrix.sum()}")

matrix:
[[ 83  34  24   3  63]
 [100  46  21  57  10]
 [ 65  61  55  82  48]
 [ 62  91  42  20  29]
 [ 92  78  82  36  77]]
sum of elements = 1361


#15 Створіть дві матриці розміром 4x4, заповніть їх випадковими цілими числами в діапазоні від 1 до 10 та знайдіть їхню різницю.

In [15]:
matrix_1 = np.random.randint(1, 11, size=(4, 4), dtype=int)
matrix_2 = np.random.randint(1, 11, size=(4, 4), dtype=int)
difference = matrix_1 - matrix_2
print(f"matrix_1:\n{matrix_1}")
print(f"matrix_2:\n{matrix_2}")
print(f"difference:\n{difference}")

matrix_1:
[[ 3  4 10  5]
 [ 6  5  1  4]
 [ 8  8  2  6]
 [10  5  9  7]]
matrix_2:
[[10  2  1  3]
 [10  4  3  3]
 [ 5  2  5  8]
 [ 4  8  2  5]]
difference:
[[-7  2  9  2]
 [-4  1 -2  1]
 [ 3  6 -3 -2]
 [ 6 -3  7  2]]


#16 Створіть матрицю розміром 3x3, заповніть її випадковими дійсними числами в діапазоні від 0 до 1 та знайдіть вектор-стовпчик, що містить суму елементів кожного рядка матриці.

In [29]:
matrix = np.random.randint(0, 2, size=(3, 3), dtype=int)
row_sums = np.sum(matrix, axis=1)
column_vector = row_sums.reshape(-1, 1)
print(f"matrix:\n{matrix}")
print(f"sum elements:\n{column_vector}")


matrix:
[[0 1 1]
 [1 1 0]
 [0 1 0]]
sum elements:
[[2]
 [2]
 [1]]


#17 Створіть матрицю розміром 3x4 з довільними цілими числами і створінь матрицю з квадратами цих чисел.

In [30]:
matrix = np.random.randint(1, 11, size=(3, 4), dtype=int)
print(f"matrix:\n{matrix}")
print(f"square_matrix\n{matrix**2}")

matrix:
[[ 1 10  4  3]
 [ 6  5  8 10]
 [ 6  3  4  2]]
square_matrix
[[  1 100  16   9]
 [ 36  25  64 100]
 [ 36   9  16   4]]


#18 Створіть вектор розміром 4, заповніть його випадковими цілими числами в діапазоні від 1 до 50 та знайдіть вектор з квадратними коренями цих чисел.

In [44]:
vector = np.random.randint(1, 51, size=4, dtype=int)
print(f"vector:\n{vector}")
print(f"vector root:\n{np.sqrt(vector)}")

vector:
[48 37  8  4]
vector root:
[6.92820323 6.08276253 2.82842712 2.        ]
